feat(pkh-tezos): remove @taquito/utils for stablelib
ceramicnetwork/js-did pull request #147
Opened 2023-02-24 16:51 UTC by zachferland

need to test/review further

2023-02-24 19:02 UTC, zachferland commented
Clearly not working, add simple tests for the two funcs i tried to implement 

maybe some differences between handling uin8arrays/enc/dec, nothing obviously wrong yet

2023-02-25 08:55 UTC, oed requested changes
Lgtm, just one request

2023-02-25 08:55 UTC, oed commented on packages/pkh-tezos/test/index.test.ts
> +import { char2Bytes, verifySignature as taquitoVerifySignature, getPkhfromPk as taquitoGetPkhfromPk } from '@taquito/utils'
Can we just generate some test vectors so that we don't need to include the `@taquito` deps at all?

2023-02-26 15:41 UTC, oed approved these changes
Lets actually merge this and get into js-ceramic asap. We can address test vectors later

2023-02-26 16:15 UTC, merged